update svelte and fix storybook error
torrust/torrust-website-v1 pull request #163
Opened 2024-04-23 21:01 UTC by grmbyrn

I have made the following changes so that the [Storybook can run in dev mode](https://github.com/torrust/torrust-website/issues/104)

* Svelte Version Update: I have upgraded our project to use svelte@4.2.15 version of Svelte. This update includes several enhancements and bug fixes and corrects some of the errors in the Storybook.
* Storybook Errors Fix: I have investigated and resolved the errors we were encountering in Storybook. The warning message was coming from Vite's Svelte plugin, indicating that the `<Hst.Story>` component would not be reactive if Hst.Story changes. To make it reactive, I used `<svelte:component this={Hst.Story} />` instead of `<Hst.Story />`.

Before;
```
<Hst.Story title="Organisms/Header" layout={{ type: 'single', iframe: true }}>
	<Hst.Variant title="Transparent Background">
		<Header />
	</Hst.Variant>

	<Hst.Variant title="With Background">
		<Header showBackground />
	</Hst.Variant>
</Hst.Story>
```

After:
```
<svelte:component this={Hst.Story} title="Organisms/Header" layout={{ type: 'single', iframe: true }}>
    <Hst.Variant title="Transparent Background">
        <Header />
    </Hst.Variant>

    <Hst.Variant title="With Background">
        <Header showBackground />
    </Hst.Variant>
</svelte:component>
```

2024-04-24 11:19 UTC, josecelano requested changes
Hi @grmbyrn, this needs a rebase and [it's not working with NPM](https://github.com/torrust/torrust-website/actions/runs/8807165486/job/24173617167?pr=163).

2024-04-24 11:20 UTC, josecelano commented
> Hi @grmbyrn, this needs a rebase and [it's not working with NPM](https://github.com/torrust/torrust-website/actions/runs/8807165486/job/24173617167?pr=163).

We are using NPM in CI, so I've removed the `yarn.lock` from the repo.

2024-04-24 14:50 UTC, grmbyrn commented
> > Hi @grmbyrn, this needs a rebase and [it's not working with NPM](https://github.com/torrust/torrust-website/actions/runs/8807165486/job/24173617167?pr=163).
> 
> We are using NPM in CI, so I've removed the `yarn.lock` from the repo.

Hi @josecelano I just did the rebase. Let me know if that was okay or if something needs to be done.

2024-04-24 16:10 UTC, josecelano commented
> > > Hi @grmbyrn, this needs a rebase and [it's not working with NPM](https://github.com/torrust/torrust-website/actions/runs/8807165486/job/24173617167?pr=163).
> > 
> > 
> > We are using NPM in CI, so I've removed the `yarn.lock` from the repo.
> 
> Hi @josecelano I just did the rebase. Let me know if that was okay or if something needs to be done.

HI @grmbyrnI would suggest a couple of things:

### Mandatory

- Resolve conflicts: you have to remove the `yarn.lock` file in your branch.
- Rebase your branch on top of the latest develop branch.
- Push force

### Optional but nice

You could squash the commits into one single commit.

2024-04-24 16:27 UTC, grmbyrn commented
> > > > Hi @grmbyrn, this needs a rebase and [it's not working with NPM](https://github.com/torrust/torrust-website/actions/runs/8807165486/job/24173617167?pr=163).
> > > 
> > > 
> > > We are using NPM in CI, so I've removed the `yarn.lock` from the repo.
> > 
> > 
> > Hi @josecelano I just did the rebase. Let me know if that was okay or if something needs to be done.
> 
> HI @grmbyrnI would suggest a couple of things:
> 
> ### Mandatory
> * Resolve conflicts: you have to remove the `yarn.lock` file in your branch.
> * Rebase your branch on top of the latest develop branch.
> * Push force
> 
> ### Optional but nice
> You could squash the commits into one single commit.

Hi @josecelano I followed the mandatory steps and I think they went through okay.

2024-04-24 16:41 UTC, josecelano commented
ACK ef7c070939daac49dfafcc8feb29f228ad35b4e9

2024-04-24 16:42 UTC, josecelano commented
ACK ef7c070939daac49dfafcc8feb29f228ad35b4e9

2024-04-24 16:49 UTC, josecelano requested changes
Hi @grmbyrn the `npm install` is still failing:

https://github.com/torrust/torrust-website/actions/runs/8819898296/job/24212225090?pr=163

Make sure you use the same node version as in the CI.

2024-04-24 16:50 UTC, josecelano commented
Hi @grmbyrn. All checks below should pass.

![image](https://github.com/torrust/torrust-website/assets/58816/5319904b-f996-438a-9817-a87d3696f898)

2024-04-29 08:09 UTC, josecelano requested changes
Hi @grmbyrn there are still some warnings running `npm run lint` that can be fixed with:

`npm run format`.

2024-04-29 08:43 UTC, grmbyrn commented
> Hi @grmbyrn there are still some warnings running `npm run lint` that can be fixed with:
> 
> `npm run format`.

Hi @josecelano thanks for that. I've run `npm run format` but I'm not sure if it's solving all the issues. One thing I've noticed is that on the contributor's page, when I click on an individual contributor, I sometimes get this error:

```
NotFound [Error]: Not found: /graeme-byrne/favicons/favicon.ico
    at resolve (/Users/macbookair/Desktop/torrust-website-4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
    at resolve (/Users/macbookair/Desktop/torrust-website-4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
    at #options.hooks.handle (/Users/macbookair/Desktop/torrust-website-4/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
    at Module.respond (/Users/macbookair/Desktop/torrust-website-4/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404
}
```

This error also comes up as an error in the build. Any idea about that?

2024-04-29 09:58 UTC, josecelano commented
Hi @grmbyrn I don't see that error but I see others.

```output

> torrust-website@1.0.0 build
> vite build


vite v4.5.3 building SSR bundle for production...
✓ 196 modules transformed.

vite v4.5.3 building for production...
✓ 202 modules transformed.
.svelte-kit/output/client/_app/version.json                                                            0.03 kB │ gzip:  0.05 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-slab-vietnamese-wght-normal.4c2a824c.woff2      9.87 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-mono-vietnamese-wght-normal.1651b21a.woff2     10.26 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-mono-greek-wght-normal.5e78ebd0.woff2          14.09 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-slab-greek-wght-normal.1c0fd8b5.woff2          14.85 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-mono-cyrillic-wght-normal.f5503b96.woff2       18.60 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-slab-latin-ext-wght-normal.c5c26829.woff2      20.76 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-slab-cyrillic-wght-normal.b914dc87.woff2       21.27 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-mono-latin-ext-wght-normal.d3f58cdc.woff2      22.87 kB
.svelte-kit/output/client/.vite/manifest.json                                                         24.59 kB │ gzip:  2.16 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-slab-cyrillic-ext-wght-normal.09b79394.woff2   32.28 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-mono-latin-wght-normal.47388fbc.woff2          32.94 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-slab-latin-wght-normal.a8e42961.woff2          34.33 kB
.svelte-kit/output/client/_app/immutable/assets/roboto-mono-cyrillic-ext-wght-normal.d694a640.woff2   35.89 kB
.svelte-kit/output/client/_app/immutable/assets/5.54fb0e52.css                                         0.05 kB │ gzip:  0.07 kB
.svelte-kit/output/client/_app/immutable/assets/Image.0954db74.css                                     0.06 kB │ gzip:  0.08 kB
.svelte-kit/output/client/_app/immutable/assets/1.e3eb7d9c.css                                         0.46 kB │ gzip:  0.26 kB
.svelte-kit/output/client/_app/immutable/assets/25.46720fa1.css                                        0.59 kB │ gzip:  0.24 kB
.svelte-kit/output/client/_app/immutable/assets/26.09990c21.css                                        0.63 kB │ gzip:  0.33 kB
.svelte-kit/output/client/_app/immutable/assets/3.ead8346b.css                                         0.82 kB │ gzip:  0.31 kB
.svelte-kit/output/client/_app/immutable/assets/4.4c4b0438.css                                         1.08 kB │ gzip:  0.42 kB
.svelte-kit/output/client/_app/immutable/assets/ContributorCard.eba0a3b3.css                           1.30 kB │ gzip:  0.52 kB
.svelte-kit/output/client/_app/immutable/assets/Button.b2541fdf.css                                    1.84 kB │ gzip:  0.50 kB
.svelte-kit/output/client/_app/immutable/assets/2.80e4b453.css                                         2.13 kB │ gzip:  0.63 kB
.svelte-kit/output/client/_app/immutable/assets/PostTable.b263c305.css                                 3.23 kB │ gzip:  0.93 kB
.svelte-kit/output/client/_app/immutable/assets/ContentSection.d1373631.css                            3.35 kB │ gzip:  0.95 kB
.svelte-kit/output/client/_app/immutable/assets/23.ccf52313.css                                        4.69 kB │ gzip:  1.02 kB
.svelte-kit/output/client/_app/immutable/assets/Footer.bfd184e3.css                                   30.71 kB │ gzip:  4.25 kB
.svelte-kit/output/client/_app/immutable/assets/0.1e52eefd.css                                        34.81 kB │ gzip:  7.58 kB
.svelte-kit/output/client/_app/immutable/chunks/regex.7dfa9b23.js                                      0.05 kB │ gzip:  0.06 kB
.svelte-kit/output/client/_app/immutable/chunks/each.e59479a4.js                                       0.09 kB │ gzip:  0.10 kB
.svelte-kit/output/client/_app/immutable/chunks/spread.84d39b6c.js                                     0.27 kB │ gzip:  0.19 kB
.svelte-kit/output/client/_app/immutable/chunks/meta.7a02798e.js                                       0.32 kB │ gzip:  0.23 kB
.svelte-kit/output/client/_app/immutable/chunks/index.58a9c514.js                                      0.45 kB │ gzip:  0.32 kB
.svelte-kit/output/client/_app/immutable/nodes/0.5a2e2b72.js                                           0.72 kB │ gzip:  0.47 kB
.svelte-kit/output/client/_app/immutable/nodes/22.7bb572a6.js                                          1.05 kB │ gzip:  0.64 kB
.svelte-kit/output/client/_app/immutable/nodes/17.77c50ecf.js                                          1.28 kB │ gzip:  0.74 kB
.svelte-kit/output/client/_app/immutable/nodes/21.888f81f2.js                                          1.33 kB │ gzip:  0.79 kB
.svelte-kit/output/client/_app/immutable/nodes/5.05ba95aa.js                                           1.36 kB │ gzip:  0.78 kB
.svelte-kit/output/client/_app/immutable/chunks/Image.d2cb7e01.js                                      1.37 kB │ gzip:  0.76 kB
.svelte-kit/output/client/_app/immutable/nodes/19.6634017b.js                                          1.53 kB │ gzip:  0.88 kB
.svelte-kit/output/client/_app/immutable/chunks/github.7979f8b0.js                                     1.68 kB │ gzip:  0.84 kB
.svelte-kit/output/client/_app/immutable/nodes/26.091fc6ff.js                                          1.73 kB │ gzip:  0.59 kB
.svelte-kit/output/client/_app/immutable/nodes/24.426e2994.js                                          1.74 kB │ gzip:  0.92 kB
.svelte-kit/output/client/_app/immutable/nodes/18.74319e1b.js                                          1.89 kB │ gzip:  1.04 kB
.svelte-kit/output/client/_app/immutable/chunks/Icon.1cb30586.js                                       1.97 kB │ gzip:  1.02 kB
.svelte-kit/output/client/_app/immutable/chunks/index.23774679.js                                      2.31 kB │ gzip:  1.21 kB
.svelte-kit/output/client/_app/immutable/nodes/20.6e61a5f4.js                                          2.39 kB │ gzip:  1.25 kB
.svelte-kit/output/client/_app/immutable/chunks/singletons.bfbe3d6e.js                                 2.46 kB │ gzip:  1.27 kB
.svelte-kit/output/client/_app/immutable/chunks/PostTable.44f59d0c.js                                  2.61 kB │ gzip:  1.13 kB
.svelte-kit/output/client/_app/immutable/nodes/1.093982a9.js                                           2.64 kB │ gzip:  1.33 kB
.svelte-kit/output/client/_app/immutable/chunks/Button.6a488862.js                                     3.25 kB │ gzip:  1.61 kB
.svelte-kit/output/client/_app/immutable/nodes/25.4833cc95.js                                          3.37 kB │ gzip:  1.36 kB
.svelte-kit/output/client/_app/immutable/chunks/CodeBlock.643cff78.js                                  3.43 kB │ gzip:  1.56 kB
.svelte-kit/output/client/_app/immutable/nodes/4.b50e9f4c.js                                           3.82 kB │ gzip:  1.58 kB
.svelte-kit/output/client/_app/immutable/nodes/3.e6a4cf60.js                                           5.55 kB │ gzip:  2.16 kB
.svelte-kit/output/client/_app/immutable/chunks/Callout.4d1c0543.js                                    5.78 kB │ gzip:  1.54 kB
.svelte-kit/output/client/_app/immutable/chunks/error.e876debb.js                                      6.95 kB │ gzip:  2.37 kB
.svelte-kit/output/client/_app/immutable/chunks/scheduler.86c7d657.js                                  9.04 kB │ gzip:  3.56 kB
.svelte-kit/output/client/_app/immutable/nodes/13.493f11b1.js                                          9.18 kB │ gzip:  3.25 kB
.svelte-kit/output/client/_app/immutable/nodes/9.c81b9c86.js                                           9.60 kB │ gzip:  3.55 kB
.svelte-kit/output/client/_app/immutable/chunks/ContributorCard.2ab156cd.js                            9.87 kB │ gzip:  2.93 kB
.svelte-kit/ou [...]

2024-04-29 17:56 UTC, grmbyrn commented
> Hi @grmbyrn I don't see that error but I see others.
> 
> ```
> 
> > torrust-website@1.0.0 build
> > vite build
> 
> 
> vite v4.5.3 building SSR bundle for production...
> ✓ 196 modules transformed.
> 
> vite v4.5.3 building for production...
> ✓ 202 modules transformed.
> .svelte-kit/output/client/_app/version.json                                                            0.03 kB │ gzip:  0.05 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-slab-vietnamese-wght-normal.4c2a824c.woff2      9.87 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-mono-vietnamese-wght-normal.1651b21a.woff2     10.26 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-mono-greek-wght-normal.5e78ebd0.woff2          14.09 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-slab-greek-wght-normal.1c0fd8b5.woff2          14.85 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-mono-cyrillic-wght-normal.f5503b96.woff2       18.60 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-slab-latin-ext-wght-normal.c5c26829.woff2      20.76 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-slab-cyrillic-wght-normal.b914dc87.woff2       21.27 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-mono-latin-ext-wght-normal.d3f58cdc.woff2      22.87 kB
> .svelte-kit/output/client/.vite/manifest.json                                                         24.59 kB │ gzip:  2.16 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-slab-cyrillic-ext-wght-normal.09b79394.woff2   32.28 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-mono-latin-wght-normal.47388fbc.woff2          32.94 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-slab-latin-wght-normal.a8e42961.woff2          34.33 kB
> .svelte-kit/output/client/_app/immutable/assets/roboto-mono-cyrillic-ext-wght-normal.d694a640.woff2   35.89 kB
> .svelte-kit/output/client/_app/immutable/assets/5.54fb0e52.css                                         0.05 kB │ gzip:  0.07 kB
> .svelte-kit/output/client/_app/immutable/assets/Image.0954db74.css                                     0.06 kB │ gzip:  0.08 kB
> .svelte-kit/output/client/_app/immutable/assets/1.e3eb7d9c.css                                         0.46 kB │ gzip:  0.26 kB
> .svelte-kit/output/client/_app/immutable/assets/25.46720fa1.css                                        0.59 kB │ gzip:  0.24 kB
> .svelte-kit/output/client/_app/immutable/assets/26.09990c21.css                                        0.63 kB │ gzip:  0.33 kB
> .svelte-kit/output/client/_app/immutable/assets/3.ead8346b.css                                         0.82 kB │ gzip:  0.31 kB
> .svelte-kit/output/client/_app/immutable/assets/4.4c4b0438.css                                         1.08 kB │ gzip:  0.42 kB
> .svelte-kit/output/client/_app/immutable/assets/ContributorCard.eba0a3b3.css                           1.30 kB │ gzip:  0.52 kB
> .svelte-kit/output/client/_app/immutable/assets/Button.b2541fdf.css                                    1.84 kB │ gzip:  0.50 kB
> .svelte-kit/output/client/_app/immutable/assets/2.80e4b453.css                                         2.13 kB │ gzip:  0.63 kB
> .svelte-kit/output/client/_app/immutable/assets/PostTable.b263c305.css                                 3.23 kB │ gzip:  0.93 kB
> .svelte-kit/output/client/_app/immutable/assets/ContentSection.d1373631.css                            3.35 kB │ gzip:  0.95 kB
> .svelte-kit/output/client/_app/immutable/assets/23.ccf52313.css                                        4.69 kB │ gzip:  1.02 kB
> .svelte-kit/output/client/_app/immutable/assets/Footer.bfd184e3.css                                   30.71 kB │ gzip:  4.25 kB
> .svelte-kit/output/client/_app/immutable/assets/0.1e52eefd.css                                        34.81 kB │ gzip:  7.58 kB
> .svelte-kit/output/client/_app/immutable/chunks/regex.7dfa9b23.js                                      0.05 kB │ gzip:  0.06 kB
> .svelte-kit/output/client/_app/immutable/chunks/each.e59479a4.js                                       0.09 kB │ gzip:  0.10 kB
> .svelte-kit/output/client/_app/immutable/chunks/spread.84d39b6c.js                                     0.27 kB │ gzip:  0.19 kB
> .svelte-kit/output/client/_app/immutable/chunks/meta.7a02798e.js                                       0.32 kB │ gzip:  0.23 kB
> .svelte-kit/output/client/_app/immutable/chunks/index.58a9c514.js                                      0.45 kB │ gzip:  0.32 kB
> .svelte-kit/output/client/_app/immutable/nodes/0.5a2e2b72.js                                           0.72 kB │ gzip:  0.47 kB
> .svelte-kit/output/client/_app/immutable/nodes/22.7bb572a6.js                                          1.05 kB │ gzip:  0.64 kB
> .svelte-kit/output/client/_app/immutable/nodes/17.77c50ecf.js                                          1.28 kB │ gzip:  0.74 kB
> .svelte-kit/output/client/_app/immutable/nodes/21.888f81f2.js                                          1.33 kB │ gzip:  0.79 kB
> .svelte-kit/output/client/_app/immutable/nodes/5.05ba95aa.js                                           1.36 kB │ gzip:  0.78 kB
> .svelte-kit/output/client/_app/immutable/chunks/Image.d2cb7e01.js                                      1.37 kB │ gzip:  0.76 kB
> .svelte-kit/output/client/_app/immutable/nodes/19.6634017b.js                                          1.53 kB │ gzip:  0.88 kB
> .svelte-kit/output/client/_app/immutable/chunks/github.7979f8b0.js                                     1.68 kB │ gzip:  0.84 kB
> .svelte-kit/output/client/_app/immutable/nodes/26.091fc6ff.js                                          1.73 kB │ gzip:  0.59 kB
> .svelte-kit/output/client/_app/immutable/nodes/24.426e2994.js                                          1.74 kB │ gzip:  0.92 kB
> .svelte-kit/output/client/_app/immutable/nodes/18.74319e1b.js                                          1.89 kB │ gzip:  1.04 kB
> .svelte-kit/output/client/_app/immutable/chunks/Icon.1cb30586.js                                       1.97 kB │ gzip:  1.02 kB
> .svelte-kit/output/client/_app/immutable/chunks/index.23774679.js                                      2.31 kB │ gzip:  1.21 kB
> .svelte-kit/output/client/_app/immutable/nodes/20.6e61a5f4.js                                          2.39 kB │ gzip:  1.25 kB
> .svelte-kit/output/client/_app/immutable/chunks/singletons.bfbe3d6e.js                                 2.46 kB │ gzip:  1.27 kB
> .svelte-kit/output/client/_app/immutable/chunks/PostTable.44f59d0c.js                                  2.61 kB │ gzip:  1.13 kB
> .svelte-kit/output/client/_app/immutable/nodes/1.093982a9.js                                           2.64 kB │ gzip:  1.33 kB
> .svelte-kit/output/client/_app/immutable/chunks/Button.6a488862.js                                     3.25 kB │ gzip:  1.61 kB
> .svelte-kit/output/client/_app/immutable/nodes/25.4833cc95.js                                          3.37 kB │ gzip:  1.36 kB
> .svelte-kit/output/client/_app/immutable/chunks/CodeBlock.643cff78.js                                  3.43 kB │ gzip:  1.56 kB
> .svelte-kit/output/client/_app/immutable/nodes/4.b50e9f4c.js                                           3.82 kB │ gzip:  1.58 kB
> .svelte-kit/output/client/_app/immutable/nodes/3.e6a4cf60.js                                           5.55 kB │ gzip:  2.16 kB
> .svelte-kit/output/client/_app/immutable/chunks/Callout.4d1c0543.js                                    5.78 kB │ gzip:  1.54 kB
> .svelte-kit/output/client/_app/immutable/chunks/error.e876debb.js                                      6.95 kB │ gzip:  2.37 kB
> .svelte-kit/output/client/_app/immutable/chunks/scheduler.86c7d657.js                                  9.04 kB │ gzip:  3.56 kB
> .svelte-kit/output/client/_app/immutable/nodes/13.493f11b1.js                                          9.18 kB │ gzip:  3.25 kB
> .svelte-kit/output/client/_app/immutable/nodes/9.c81b9c86.js                                           9.60 kB │ gzip:  3.55 kB
 [...]

2024-04-29 18:15 UTC, josecelano commented
Ok, @grmbyrn let's merge what is fixed so far and I will open independent issues for each of the remaining bugs. At least we can run the storybook now.

2024-04-29 18:15 UTC, josecelano commented
ACK a2f0deaac45f69fd3d8ce620c0652bdd766cb4c4

2024-04-29 18:17 UTC, merged